### ISSUE TITLE
Methods for new block and default block 

### ISSUE THREAD

**Issue by marcelauer** [Liberty009/rsmdf#17]
Hi,

first I have to say you did a very good job so far!

I am currently working on a related task at my job and I stumbled upon this pattern in the code of every block type: [Example](https://github.com/Liberty009/rsmdf/blob/master/src/mdf4/cg_block.rs#:~:text=%7D-,impl%20Block%20for%20Cgblock%20%7B,%7D,-fn%20read) 
There is always a method to create a new block of the chosen type and a method to create a default block. Somehow the method for the default block is never used. Was there a specific solution you had in mind or has this become redundant?

**Comment by Liberty009** [comment]
Hi, 

The default is to satisfy a recommendation from clippy that if a new function exists, a default function should be available. It currently isn't necessary and possibly could be removed. There may be a use for it when the MDF file creation side gets developed.

Thanks for looking at this repo

**Comment by marcelauer** [comment]
Hi, thanks for your reply. I am currently working on the file creation part for the MDF4.1 standard and I think i will remove the default blocks. I have spoken with my colleagues and we are happy to contribute to your repository once everything is finalized and tested on our end. 

Have a nice week!
